name: Deploy Kraken to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      GITHUB_WORSPACE: /home/ec2-user/

    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check env
      - run: |
          echo $GITHUB_WORKSPACE
    #   - name: Create .env file
    #     run: |
    #       sudo newgrp docker
    #       echo "TOKEN=${{ secrets.TOKEN }}" >> .env
    #       echo "GOD_ID=${{ secrets.GOD_ID }}" >> .env
    #     working_directory: $GITHUB_WORSPACE

    #  - name: SSH into EC2 and Deploy
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.HOST_NAME }}
    #       username: ${{ secrets.USER_NAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: 
    #         sudo newgrp docker
    #         cd "$GITHUB_WORSPACE"
    #         bash ./build.sh



